INSERT INTO `tbl_extra_pages` (`epage_id`, `epage_identifier`, `epage_type`, `epage_content_for`, `epage_active`, `epage_default`, `epage_default_content`) VALUES (NULL, 'Admin Zones', '45', '1', '1', '0', '<br />\r\n\r\n<h2>Zones Content File</h2> <br />\r\n\r\n<h3>Zone Identifier</h3>User defined unique identifier for the Zone. This works as a unique key for the system to identify a particular Zone. <br />\r\n<br />\r\n\r\n<h3>Zone name</h3>User defined name for the Zone.<br />\r\n<br />\r\n\r\n<h3>Active</h3>User defined field to mark a particular zone as active in the system or not. Possible inputs for this field are \'Yes\' &amp; \'No\'. Default value should be set as \'Yes\'.');
INSERT INTO `tbl_extra_pages_lang` (`epagelang_epage_id`, `epagelang_lang_id`, `epage_label`, `epage_content`) VALUES ((select epage_id from tbl_extra_pages where epage_type='45'), '1', 'Admin Zones', '<br />\r\n\r\n<h2>Zones Content File</h2> <br />\r\n\r\n<h3>Zone Identifier</h3>User defined unique identifier for the Zone. This works as a unique key for the system to identify a particular Zone. <br />\r\n<br />\r\n\r\n<h3>Zone name</h3>User defined name for the Zone.<br />\r\n<br />\r\n\r\n<h3>Active</h3>User defined field to mark a particular zone as active in the system or not. Possible inputs for this field are \'Yes\' &amp; \'No\'. Default value should be set as \'Yes\'.');
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_unlimited', '1', 'Unlimited', '1') ON DUPLICATE KEY UPDATE label_caption = 'Unlimited';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_shipping_by_other_method', '1', 'Shipping By Other Method', '1') ON DUPLICATE KEY UPDATE label_caption = 'Shipping By Other Method';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_app_reached_download_limit', '1', 'You have reached download limit', '1') ON DUPLICATE KEY UPDATE label_caption = 'You have reached download limit';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_password_must_be_atleast_eight_characters_long_and_alphanumberic', '1', 'Password Must Be Atleast Eight Characters Long And Alphanumeric', '1') ON DUPLICATE KEY UPDATE label_caption = 'Password Must Be Atleast Eight Characters Long And Alphanumeric';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_not_accessible', '1', 'Not Accessible', '1') ON DUPLICATE KEY UPDATE label_caption = 'Not Accessible';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_open_settings', '1', 'Open Setting', '1') ON DUPLICATE KEY UPDATE label_caption = 'Open Setting';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_choose_category', '1', 'Choose Category', '1') ON DUPLICATE KEY UPDATE label_caption = 'Choose Category';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_select_category', '1', 'Select Category', '1') ON DUPLICATE KEY UPDATE label_caption = 'Select Category';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_select_brand', '1', 'Select Brand', '1') ON DUPLICATE KEY UPDATE label_caption = 'Select Brand';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_please_select_the_category', '1', 'Please select the category', '1') ON DUPLICATE KEY UPDATE label_caption = 'Please select the category';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_please_select_brand', '1', 'Please select the brand', '1') ON DUPLICATE KEY UPDATE label_caption = 'Please select the brand';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_payment_scuccess', '1', 'Payment Success', '1') ON DUPLICATE KEY UPDATE label_caption = 'Payment Success';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_verify_otp', '1', 'Verify OTP', '1') ON DUPLICATE KEY UPDATE label_caption = 'Verify OTP';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_reset_password', '1', 'Reset Password', '1') ON DUPLICATE KEY UPDATE label_caption = 'Reset Password';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_items_are_not_available_for_pickup', '1', 'Items not available for Pickup', '1') ON DUPLICATE KEY UPDATE label_caption = 'Items not available for Pickup';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_items_are_not_available_for_pickup_ship_entire_order', '1', 'Items not available for pickup ship entire order', '1') ON DUPLICATE KEY UPDATE label_caption = 'Items not available for pickup ship entire order';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_error', '1', 'Error', '1') ON DUPLICATE KEY UPDATE label_caption = 'Error';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_new_version', '1', 'New Version', '1') ON DUPLICATE KEY UPDATE label_caption = 'New Version';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_later', '1', 'Later', '1') ON DUPLICATE KEY UPDATE label_caption = 'Later';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_error_saving_file', '1', 'Error downloading file', '1') ON DUPLICATE KEY UPDATE label_caption = 'Error downloading file';
INSERT IGNORE INTO `tbl_language_labels` ( `label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('app_error_downloading_file', '1', 'Error downloading file', '1') ON DUPLICATE KEY UPDATE label_caption = 'Error downloading file';

/* Update all stripe connect standard account users default form submited to 1. Because no form required. */
INSERT IGNORE INTO tbl_user_meta (usermeta_user_id, usermeta_key, usermeta_value)
  SELECT usermeta_user_id, 'stripe_form_submitted', '1' 
  FROM tbl_user_meta WHERE usermeta_key LIKE 'stripe_account_type' AND usermeta_value LIKE 'standard';
/* Update all stripe connect standard account users default form submited to 1. Because no form required. */

-- ---------Task 86672 Stripe Connect Changes ------ --
INSERT IGNORE INTO `tbl_language_labels` (`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES
('LBL_INDIVIDUAL_ADDITIONAL_IDENTIFYING_DOCUMENT', 1, 'A document showing address, either a passport, local ID card, or utility bill from a well-known utility company.', 1),
('LBL_STRIPE_CONNECT_PAYOUT_INTERVAL_DESC', 1, 'How frequently available funds are paid out. One of: daily, manual, weekly, or monthly. Default is daily.', 1),
('LBL_STRIPE_CONNECT_PAYOUT_DELAY_DAYS_DESC', 1, 'The number of days charge funds are held before being paid out. May also be set to minimum, representing the lowest available value for the account country. Default is minimum. The delay_days parameter does not apply when the interval is manual.', 1),
('LBL_STRIPE_CONNECT_WEEK_DAY_DESC', 1, 'The day of the week when available funds are paid out, specified as monday, tuesday, etc. (required and applicable only if interval is weekly.)', 1),
('LBL_STRIPE_CONNECT_MONTH_DAY_DESC', 1, 'The day of the month when available funds are paid out, specified as a number between 1–31. Payouts nominally scheduled between the 29th and 31st of the month are instead sent on the last day of a shorter month. Required and applicable only if interval is monthly.', 1)
ON DUPLICATE KEY UPDATE label_caption = VALUES(label_caption), label_type = 1;
-- ---------Task 86672 Stripe Connect Changes ------ -- 

INSERT IGNORE INTO `tbl_plugins_lang` (`pluginlang_plugin_id`, `pluginlang_lang_id`, `plugin_name`, `plugin_description`) VALUES
((SELECT plugin_id FROM `tbl_plugins` WHERE plugin_code = "GoogleShoppingFeed"), 1, 'Google Shopping Feed', '<h6 class=\"mt-2\">Please Follow Below Steps To Get Service Account Detail :</h6>\r\n<ul class=\"listing--bullet\">      \r\n	<li>Visit <a class=\"link\" href=\"https://console.developers.google.com\" target=\"_blank\">Google Console</a></li>            \r\n    <li>Click on <span style=\"font-weight: bold;\">Navigation Menu</span> (Breadcrumb Icon).</li>            \r\n	<li>Open the <span style=\"font-weight: bold;\">IAM &amp; Admin</span> page in the Cloud Console.</li>            \r\n	<li>Click <span style=\"font-weight: bold;\">Select a project</span>, choose a project, and click <span style=\"font-weight: bold;\">Open.</span></li>            \r\n	<li>In the left nav, click <span style=\"font-weight: bold;\">Service accounts.</span></li>            \r\n	<li>Find the row of the service account that you want to create a key for. Follow below steps.</li>\r\n    <li>Steps > In that row, click the <span style=\"font-weight: bold;\">Actions <i class=\"fa fa-ellipsis-v\"></i></span> button, and then click <span style=\"font-weight: bold;\">Create key/Manage Keys.</span></li>\r\n    <li>If service account row not listing on this page. Then click on <span style=\"font-weight: bold;\">Create service account</span> and fill the required information and follow above mentioned steps.</li>           \r\n	<li>Select a <span style=\"font-weight: bold;\">Key type</span> and click <span style=\"font-weight: bold;\">Create.</span> - OR - Select <span style=\"font-weight: bold;\">Add Key</span> and click <span style=\"font-weight: bold;\">Create new key</span> and select <span style=\"font-weight: bold;\">JSON</span> hit Create.</li>\r\n    <li>A JSON file will be downloaded. Open that JSON file copy whole data inside that file and paste it in above <span style=\"font-weight: bold;\">Service account detail</span> input box.</li>\r\n    <li>Hit Save Button</li>\r\n</ul>\r\n<div class=\"divider\"></div>\r\n<h6 class=\"mt-4\">Linking Service Account with Merchant Center Account:</h6>\r\n<ul class=\"listing--bullet\">\r\n    <li>Open that JSON file again and search <span style=\"font-weight: bold;\">client_email</span> and copy its value <span style=\"font-weight: bold;\">XXXX@XXXXXXX.iam.gserviceaccount.com</span>.</li>\r\n    <li>Now visit <a class=\"link\" href=\"https://merchants.google.com/\" target=\"_blank\">Merchant Center</a> and login to your connected Merchant Account.</li>\r\n    <li>Click on the Gear Icon <i class=\"fa fa-cog\"></i> > Account access > Add User > Paste that copied client_email value <span style=\"font-weight: bold;\">XXXX@XXXXXXX.iam.gserviceaccount.com</span> inside.</li>\r\n    <li>Assign Permissions accordingly and save that settings.</li>\r\n</ul>')
ON DUPLICATE KEY UPDATE plugin_description = VALUES(plugin_description);

-- -----------Stripe Connect Mandatory Check. ---------- --
INSERT IGNORE INTO `tbl_plugin_settings` (`pluginsetting_plugin_id`, `pluginsetting_key`, `pluginsetting_value`) VALUES 
((SELECT plugin_id FROM `tbl_plugins` WHERE `plugin_code` LIKE 'StripeConnect'), 'stripe_connect_mandatory', '1')
ON DUPLICATE KEY UPDATE pluginsetting_value = 1;
-- -----------Stripe Connect Mandatory Check. ---------- --

ALTER TABLE `tbl_user_transactions` ADD INDEX( `utxn_user_id`);